# Generated by Django 5.1.2 on 2024-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0003_remove_propertyimage_caption_propertyimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
