# Generated by Django 5.1.2 on 2024-12-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0004_property_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
