# Generated by Django 5.1.2 on 2024-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0005_remove_property_created_at_alter_propertyimage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
