# Generated by Django 5.1.2 on 2024-12-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0006_property_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Property_app.tenant'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Appartment', 'Appartment'), ('House', 'House'), ('Commercial', 'Commercial')], max_length=20),
        ),
    ]
