# Generated by Django 5.1.2 on 2024-12-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0007_lease_buyer_property_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='main',
        ),
    ]
