# Generated by Django 5.1.2 on 2024-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property_app', '0009_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
